### ISSUE TITLE
求详细讲解下RouterUri这个注解, 代码注册intent-filter.

### ISSUE THREAD

**Issue by wu464995183** [meituan/WMRouter#1]

**Comment by jzj1993** [comment]
只有外部跳转会经过IntentFilter匹配，打开统一的中转Activity，中转Activity再调用Router分发，Router内部直接通过代码找到目标Activity，显式跳转。对于内部跳转，直接调用Router，也是通过代码找到Activity再显式跳转。

**Comment by wu464995183** [comment]
吆西, 吆西,  还以为有什么办法可以动态的设置activity的IntentFilter呢, 非常感谢你的解答...
