### ISSUE TITLE
为什么最小api是16

### ISSUE THREAD

**Issue by zhangkuo0216** [meituan/WMRouter#11]

**Comment by zhangkuo0216** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.sankuai.waimai.router:router:1.0.41] /Users/mac/.gradle/caches/transforms-1/files-1.1/router-1.0.41.aar/e0026560c6ebc6f667ef1f72f7599244/AndroidManifest.xml as the library might be using APIs not available in 15
  	Suggestion: use a compatible library with a minSdk of at most 15,
  		or increase this project's minSdk version to at least 16,
  		or use tools:overrideLibrary="com.sankuai.waimai.router" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by jzj1993** [comment]
在Application工程的Manifest配置一下，覆盖SDK中的版本即可
<manifest>
    <uses-sdk tools:overrideLibrary="com.sankuai.waimai.router"/>
</manifest>
