### ISSUE TITLE
window  AS  build 导致无法跳转页面

### ISSUE THREAD

**Issue by zdongcoding** [meituan/WMRouter#14]
多 Module  的情况下   配置 PageUri   无法跳转页面 404 

能生成 apt 文件 但是ServiceLoader 无法加载

**Comment by tracyxia716** [comment]
我再windows电脑上也遇到了这个问题，mac和linux上编译就是好的

**Comment by jzj1993** [comment]
感谢反馈……开发的时候用的都是Mac和Linux，没有在Windows上测试，后续会修复~
