### ISSUE TITLE
mac 运行不通过麻烦看一下呢

### ISSUE THREAD

**Issue by chenxiaokai** [meituan/WMRouter#17]
Unable to add Transform 'dependencyChecker' on variant 'debug': requested streams not available: []+[PROJECT_LOCAL_DEPS, SUB_PROJECTS_LOCAL_DEPS, EXTERNAL_LIBRARIES] / [CLASSES]

**Comment by chenxiaokai** [comment]
![_b90b8eea-e29b-421e-b85d-9450f114599d](https://user-images.githubusercontent.com/8064129/46779271-8e639e00-cd49-11e8-8262-e6ed016c147f.png)

**Comment by jzj1993** [comment]
这个是直接克隆下来的代码运行不了？这个错误和WMRouter插件没关系，怀疑是Gradle版本不对。
先看下gradle/wrapper/gradle-wrapper.properties有没有被修改。然后试下命令行调用gradlew能不能编译
```bash
# mac/linux
./gradlew :demoapp:assembleDebug
# windows
./gradlew.bat :demoapp:assembleDebug
```
如果命令行编译没问题，应该是Android Studio配置的问题，检查下设置里面的Gradle是不是用的Gradle Wrapper。

**Comment by chenxiaokai** [comment]
谢谢回复，通过命令行可以运行成功。

**Comment by tankcong** [comment]
同样的问题，只能run gradle task，直接导入studio无法启动demoapp

**Comment by tankcong** [comment]
同样的问题，只能run gradle tasks，直接导入studio再run demoapp就报这个错，
Android Studio 3.2 rc2，确认勾选了Using default gradle wrapper.

**Comment by Knight-ZXW** [comment]
> 这个是直接克隆下来的代码运行不了？这个错误和WMRouter插件没关系，怀疑是Gradle版本不对。
> 先看下gradle/wrapper/gradle-wrapper.properties有没有被修改。然后试下命令行调用gradlew能不能编译
> 
> ```shell
> # mac/linux
> ./gradlew :demoapp:assembleDebug
> # windows
> ./gradlew.bat :demoapp:assembleDebug
> ```
> 
> 如果命令行编译没问题，应该是Android Studio配置的问题，检查下设置里面的Gradle是不是用的Gradle Wrapper。

打开instant run就会出现这个错误，关闭之后就好了

**Comment by guozhiwei2007** [comment]
> 谢谢回复，通过命令行可以运行成功。

请问下，最后你是怎么解决的这个问题？

**Comment by guozhiwei2007** [comment]
我的已经解决了， 也是打开instant run的问题，关闭之后就好了。
