### ISSUE TITLE
关于参数解析的一些建议

### ISSUE THREAD

**Issue by liujingg** [meituan/WMRouter#19]
1.  接入文档需完善  kotlin下kapt替换annotationProcessor；
2. 目标页面的参数通过外部标准url传参与extra传参需要分别单独解析，而且还要匹配类型，最好能自动注入或者能自动提取url中参数；

**Comment by GuolinYao** [comment]
请问如何覆写ActivityLauncher，在启动Activity前把参数统一解析放到Intent的extra中，如何统一解析？

**Comment by jzj1993** [comment]
> 请问如何覆写ActivityLauncher，在启动Activity前把参数统一解析放到Intent的extra中，如何统一解析？

`RouterComponents. setActivityLauncher()`，设置一个自定义的ActivityLauncher就可以了~

**Comment by GuolinYao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    请问如何做到统一解析呢？不是很明白
    
        
            
        
    
    
      
    
        
            
    
        
            
                
                    
                        
                    
                    
                        
                            635142285
                            
                            
                                
                                    635142285@qq.com
                                
                        
                    
                
            
        
    

        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年02月11日 00:05，江子健<notifications@github.com> 写道： 




请问如何覆写ActivityLauncher，在启动Activity前把参数统一解析放到Intent的extra中，如何统一解析？



RouterComponents. setActivityLauncher()，设置一个自定义的ActivityLauncher就可以了~



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
