### ISSUE TITLE
gradle3.0和2.0兼容问题

### ISSUE THREAD

**Issue by zhoukai0203** [meituan/WMRouter#22]
Required: EXTERNAL_LIBRARIES, PROJECT. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS
建议将gradle升级到3.0

**Comment by AurelionX** [comment]
@jzj1993 项目升级到AS3.0之后出现了类似问题，

**Comment by yaodiwei** [comment]
同楼上。使用classpath'com.android.tools.build:gradle:3.2.1'和gradle4.6
出现错误Unexpected scopes found in folder '/Users/Yao/zx/dihealth_hub/app/build/intermediates/transforms/WMRouter/debug'. Required: EXTERNAL_LIBRARIES, PROJECT. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

**Comment by yaodiwei** [comment]
感觉跟我这样配置有关？
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation("com.sankuai.waimai.router:router:1.1.0") {
        exclude module: 'support-annotations'
        exclude module: 'support-media-compat'
        exclude module: 'support-v4'
    }

或者跟我用上了最新版本的butterknife有关？依赖包有冲突？

**Comment by jzj1993** [comment]
@zhoukai0203 @AurelionX @yaodiwei  我这边没遇到你们说的这个问题，但是已经有多个人反馈了。重新发布了一个版本，把WMRouter升级到1.1.2再试试吧。

**Comment by zhoukai0203** [comment]
这个是有项目包涵的问题，最简单的demo都存在问题，app包涵library的module,再写一个other的module也包含library,app同时包含library和other就会出上面的问题，arouter不存在此问题

**Comment by jzj1993** [comment]
@Ttxy0105 不好意思，JCenter的提交出了点问题，已经重新提交审核通过了，再试一下吧~
