### ISSUE TITLE
Could not find common.jar (android.arch.core:common:1.0.0)

### ISSUE THREAD

**Issue by hanshengjian** [meituan/WMRouter#25]
编译的时候提示 Could not find common.jar (android.arch.core:common:1.0.0).
Searched in the following locations:
    https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar

**Comment by jzj1993** [comment]
应该是jCenter连接不上，配置一下代理，或者试试国内Maven镜像~
