### ISSUE TITLE
Could not find com.sankuai.waimai.router:plugin:1.1.2.

### ISSUE THREAD

**Issue by yuehongjie** [meituan/WMRouter#26]
下载项目后，直接用 AndroidStudio 打开，没有修改任何配置，

错误日志如下：

Could not find com.sankuai.waimai.router:plugin:1.1.2.
Searched in the following locations:
    file:/C:/Users/Administrator.cedar-PC/.m2/repository/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.pom
    file:/C:/Users/Administrator.cedar-PC/.m2/repository/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.jar
    http://maven.aliyun.com/nexus/content/groups/public/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.pom
    http://maven.aliyun.com/nexus/content/groups/public/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.jar
    https://maven.google.com/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.pom
    https://maven.google.com/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.jar
    https://jcenter.bintray.com/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.pom
    https://jcenter.bintray.com/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.jar
    https://repo.maven.apache.org/maven2/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.pom
    https://repo.maven.apache.org/maven2/com/sankuai/waimai/router/plugin/1.1.2/plugin-1.1.2.jar

改 VERSION_NAME=1.1.0 可以正常下载

**Comment by jzj1993** [comment]
不好意思，JCenter的提交出了点问题，已经重新提交审核通过了，再试一下吧~
