### ISSUE TITLE
key如何管理？

### ISSUE THREAD

**Issue by binIoter** [meituan/WMRouter#27]
A Module和B Module（以下简称A，B）是2个平级的Module，互相没有依赖，A要调用B的方法，通过 Router.callMethod去调用，就会涉及到A和B都持有这个key，又不想把key下沉，因为一旦下沉必然面临，多人修改，难以维护的问题，想请教一下有没有什么优雅的解决方案呢？

**Comment by jzj1993** [comment]
参考 https://github.com/meituan/WMRouter/issues/28
