### ISSUE TITLE
是否考虑把ServiceLoader单独分离出来？

### ISSUE THREAD

**Issue by guozhiqiang123** [meituan/WMRouter#30]
有考虑把ServiceLoader单独分离出来吗？觉得这个很好用！！！

**Comment by jzj1993** [comment]
最开始就是为了做Router，因为要用到注解需要加载，所以就有了ServiceLoader……暂时没有单独的ServiceLoader库，可以接入WMRouter然后只用ServiceLoader部分的功能。

App打Release包配置上Proguard，最后会把没用到的代码都清除掉，所以Router多余的部分对性能也不会有太大影响。
