### ISSUE TITLE
demoapp为啥依赖所有的子模块，才能跳转，否则会报404。不能解耦吗

### ISSUE THREAD

**Issue by JasonBlavk** [meituan/WMRouter#33]

**Comment by JasonBlavk** [comment]
app：
  compile project(path: ':demolib1')
  compile project(path: ':demokotlin')

demolib1
    compile project(path: ':demolib2')
demokotlin
    compile project(path: ':demolib2')
相当于所以都依赖了

我的做法是
添加一个完全独立的module（app不依赖），增加@RouterUr（ipath = "/jump_activity_login"），
在app里面跳转Router.startUri(context, "/jump_activity_test"); 会报404

**Comment by jzj1993** [comment]
一个完全独立的module（app不依赖），这个模块的代码不会被编译到APK里，也没有这个Activity，肯定是不能跳转的……
