### ISSUE TITLE
关于用Kotlin 编写业务模块的通信问题

### ISSUE THREAD

**Issue by liqianjiang** [meituan/WMRouter#35]
在java编写的模块掉用RouterService调用会报。
2019-02-12 19:10:58.269 10827-10827/com.example.jarson.hallobiketest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jarson.hallobiketest, PID: 10827
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
   
    关于Java和Kotlin业务模块之间的调用方式还请在demo中多多完善～谢谢。

**Comment by jzj1993** [comment]
Demo已完善，测试通过，具体代码改动详见 https://github.com/meituan/WMRouter/commit/ff9e4613e529d3961a7f0302560fea3138a003e8
