### ISSUE TITLE
添加插件 apply plugin: 'WMRouter' 后报 Unexpected scopes found in folder 

### ISSUE THREAD

**Issue by Chen-Baiyi** [meituan/WMRouter#41]
Unexpected scopes found in folder 'E:\test\Component\app\build\intermediates\transforms\WMRouter\debug'. Required: EXTERNAL_LIBRARIES, PROJECT. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

**Comment by hibate** [comment]
当前版本对 instant run 支持不足，关闭 instant run 即可: File --> Settings --> Build, Execution, Deployment --> Instant Run --> Enable Instant Run to ...
