### ISSUE TITLE
关于WMRouter不支持InstantRun的问题

### ISSUE THREAD

**Issue by Knight-ZXW** [meituan/WMRouter#43]
测试了 WMRouter的Demo工程 打开InstantRun的情况下编译会出错
错误日志为

>  What went wrong:
Execution failed for task ':demoapp:transformClassesWithInstantRunVerifierForDebug'.
> Unexpected scopes found in folder '/Users/hb/code/opensource/WMRouter/demoapp/build/intermediates/transforms/WMRouter/debug'. Required: PROJECT, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

尝试将WMRouterTransform 中的getInputTypes 方法返回值从 TransformManager.CONTENT_JARS 改为 TransformManager.CONTENT_CLASS  解决了这个问题

本身这个transform不需要对资源做处理，所以这样修改应该没什么问题

**Comment by jzj1993** [comment]
代码已合并，之前版本会生成资源文件所以用的CONTENT_JARS，新版本确实直接用CONTENT_CLASS就可以了，感谢~
