### ISSUE TITLE
关于WMRouter service moudle设计的疑问

### ISSUE THREAD

**Issue by Knight-ZXW** [meituan/WMRouter#47]
WMRouter的Service模块参考的SPI (Service Provider Interfaces) 设计，一个服务接口可以有多个服务实现，但是在实际的业务服务调用中，大部分情况下 一个服务接口只会有一个实现；
因此 WmRouter 是否可以提供  类似 Router. getService(Iservice.class) 的方法，目前是只有传入Key的实现
 Router.getService(IService.class, "key1");

**Comment by hibate** [comment]
实际业务中可能有一个实现, 也可能有多个实现。

WMRouter 实际已满足以上需求问题，`Router.getService` 方法是用来获取某个接口的特定的实现类, 而 `Router.getAllService` 方法是用来获取某个接口的所有实现类。

作为一个开源库, 不可能提供这种接口。如果实际接口有多个实现类, 那么 `Router.getService(Class<T> clazz)` 应该返回哪个实现比较合适呢？

所以实际业务中, 若能确保某个接口只有一个实现类, 可通过 `Router.getAllService` 方法获取该实现类集合, 默认取 `List.get(0)` 即可。

**Comment by Knight-ZXW** [comment]
> 实际业务中可能有一个实现, 也可能有多个实现。
> 
> WMRouter 实际已满足以上需求问题，`Router.getService` 方法是用来获取某个接口的特定的实现类, 而 `Router.getAllService` 方法是用来获取某个接口的所有实现类。
> 
> 作为一个开源库, 不可能提供这种接口。如果实际接口有多个实现类, 那么 `Router.getService(Class<T> clazz)` 应该返回哪个实现比较合适呢？
> 
> 所以实际业务中, 若能确保某个接口只有一个实现类, 可通过 `Router.getAllService` 方法获取该实现类集合, 默认取 `List.get(0)` 即可。

对于业务服务调用来说，
 一.用Key的方式感觉有点多余，因为大部分情况是只有一个实现
 二.如果用getAllService 再获取第0个的方式，代码也有点冗余（明明知道只有一个实现）

所以我的想法有2个
一：RouterService里面可以加一个注解参数 表示 该服务的实现是唯一的 （可以在编译期做检验），在Router类中再提供一个对应的方法来获取。
二：RouterService提供getService(Class<T> clazz)方法默认返回集合的第1个实现，如果发现有多个，默认抛出异常（也可以在Router的初始化时配置一下不抛出异常）。

**Comment by hibate** [comment]
> > 实际业务中可能有一个实现, 也可能有多个实现。
> > WMRouter 实际已满足以上需求问题，`Router.getService` 方法是用来获取某个接口的特定的实现类, 而 `Router.getAllService` 方法是用来获取某个接口的所有实现类。
> > 作为一个开源库, 不可能提供这种接口。如果实际接口有多个实现类, 那么 `Router.getService(Class<T> clazz)` 应该返回哪个实现比较合适呢？
> > 所以实际业务中, 若能确保某个接口只有一个实现类, 可通过 `Router.getAllService` 方法获取该实现类集合, 默认取 `List.get(0)` 即可。
> 
> 对于业务服务调用来说，
> 一.用Key的方式感觉有点多余，因为大部分情况是只有一个实现
> 二.如果用getAllService 再获取第0个的方式，代码也有点冗余（明明知道只有一个实现）
> 
> 所以我的想法有2个
> 一：RouterService里面可以加一个注解参数 表示 该服务的实现是唯一的 （可以在编译期做检验），在Router类中再提供一个对应的方法来获取。
> 二：RouterService提供getService(Class clazz)方法默认返回集合的第1个实现，如果发现有多个，默认抛出异常（也可以在Router的初始化时配置一下不抛出异常）。

按照我的理解, 作为一个服务大众的开源库, 不应该和具体业务模式耦合。且在多人开发环境下, 这样的约束条件显得不太合适：如果有人不小心多写一个实现类, 出了问题可能需要花费比较长的调试时间, 编译期检验还好说, 如果在 Runtime 运行时抛出异常, 更不好查找, 如果测试不到位, 那么生产环境下就会伴随着这种隐患了。

你们可以下载 WMRouter 源码根据你们的需求修改定制。

**Comment by Knight-ZXW** [comment]
已提供默认实现的支持 [pr](https://github.com/meituan/WMRouter/pull/56)
