### ISSUE TITLE
ERROR: Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.

### ISSUE THREAD

**Issue by xiongxianwei90** [meituan/WMRouter#51]
WmRouter 1.2.0版本，Android Studio 3.3.2，build tools插件3.2.1。gradle-wrapper 4.6
编译报错 ERROR: Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.  哪里配置的不对吗

**Comment by xiongxianwei90** [comment]
我知道了。我在library 里加了apply plugin: 'WMRouter'

**Comment by mohammedIbrahimHK** [comment]
Did you find the solution?
