### ISSUE TITLE
Unable to find method 'org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry.registerPublication(Ljava/lang/String;Lorg/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectPublication;)V'.

### ISSUE THREAD

**Issue by TyJeff2** [meituan/WMRouter#59]
clone了代码,编译不过去.错误信息如下:

`` Download https://services.gradle.org/distributions/gradle-5.2.1-all.zip (132.55 MB)
[ 96%] [ =====================================================> ] 127.94 MB
Download https://services.gradle.org/distributions/gradle-5.2.1-all.zip succeeded, took 1 m 15 s 348 ms
Unzipping ...

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry.registerPublication(Ljava/lang/String;Lorg/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectPublication;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 17s
Unable to find method 'org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry.registerPublication(Ljava/lang/String;Lorg/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectPublication;)V'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

`

**Comment by jzj1993** [comment]
这个应该是Gradle的问题，和WMRouter没有关系……
