### ISSUE TITLE
PageAnnotationHandler 和 uriAnnotationHandler 有什么区别吗

### ISSUE THREAD

**Issue by lbhbrave** [meituan/WMRouter#6]
PageAnnotationHandler 和 uriAnnotationHandler算不算一种没有host的uri，算是uriAnnotationHandler的一个子集吧。可以囊括在uriAnnotationHandler处理吧，为什么要单独拿出来一个？

**Comment by jzj1993** [comment]
通常直接用RouterUri就好了，但是有些场景下RouterPage注解也要同时用，主要是为了解决一些历史问题。关于这个可以参考美团技术博客中的相关介绍  https://tech.meituan.com/meituan_waimai_android_open_source_routing_framework.html
