### ISSUE TITLE
ServiceLoader自定义接口解耦问题

### ISSUE THREAD

**Issue by tanlzhi** [meituan/WMRouter#61]
自定义继承IService的接口都要下沉到底层模块来解耦上层业务模块吗？如果是这样的话业务模块要添加或者修改接口，岂不要更新底层平台模块。

**Comment by jzj1993** [comment]
是这样的，如果Interface不下沉到底层，业务模块就没法直接调用了。当然你可以在业务模块中获取到实现类后，使用反射的形式调用，这样就不需要特定的Interface了。
