### ISSUE TITLE
transformClassesWithMultidexlistFor##Debug

### ISSUE THREAD

**Issue by mycodey** [meituan/WMRouter#62]
clean之后编译可以正常编译
编译一次之后再次编译无法编译，错误在transformClassesWithMultidexlistFor##Debug 这个流程中。
错误信息是
java.lang.RuntimeException: com.android.build.api.tranformException: Error while generating the main dex list
原因是 
Program type already present: xxx 
 at com.andorid.build.gradle.internal.transforms.D8MainDexListTranform.tranform
 ...
duplicate_classes

@jzj1993

**Comment by jzj1993** [comment]
关闭重复问题，详见 https://github.com/meituan/WMRouter/issues/63
目前由于没有复现，无法解决，猜测可能是Android Gradle Plugin的问题。
