### ISSUE TITLE
是否对androidx提供支持？

### ISSUE THREAD

**Issue by yzhiw** [meituan/WMRouter#64]
看了下代码，fragment并没有对androidx做处理，是否可以支持？

**Comment by jzj1993** [comment]
AndroidX可以直接开启Jetifier，不需要改代码：

gradle.properties 文件：

```
android.useAndroidX=true
android.enableJetifier=true
```

参考官方文档 https://developer.android.google.cn/jetpack/androidx/migrate?hl=zh-cn
