### ISSUE TITLE
建议拦截器支持注解

### ISSUE THREAD

**Issue by sdsxwangwei** [meituan/WMRouter#65]
建议拦截器支持注解并和handler的行为一致，这样指定拦截器的时候可以不依赖class

**Comment by jzj1993** [comment]
相对于Handler来说，Interceptor比较少，所以没有做太多额外处理，直接是在Handler注解上引用了Interceptor的class。

如果提供了支持，会增加项目的复杂度，运行时容易出现Interceptor找不到的问题。

常见的Interceptor例如登录验证，不会经常变动，可以放在底层库，而业务相关的Interceptor放在和Handler相同的业务库里，这样可能更合适。
