### ISSUE TITLE
每一个模块组件都要引用插件吧

### ISSUE THREAD

**Issue by AngelRiven** [meituan/WMRouter#67]
只在 主module的gradle中 apply plugin: 'WMRouter'的话，这个插件不能找到其他module中注解生成的文件，就没法初始化了

**Comment by Knight-ZXW** [comment]
子模块只需要 使用 注解处理器就行了。
annotationProcessor 'com.sankuai.waimai.router:router:1.1.2'

注解处理器会根据模块中的注解生成service  Init类。
wmrouter plugin只需要在主模块使用，它的作用是 收集所有模块中 生成的service init类，并插入 相关注册方法

**Comment by AngelRiven** [comment]
OK，了解
