### ISSUE TITLE
ServiceLoader模块获取到的实例只能调用其实现的父类或者接口的方法是吗

### ISSUE THREAD

**Issue by AngelRiven** [meituan/WMRouter#69]
我想在模块lib1中获取模块lib2中的一个类，这个类的实现接口或者父类都在lib2模块中，那我怎么才能在lib1模块中拿到这个类，并调用这个类的方法呢

**Comment by Knight-ZXW** [comment]
lib2的职责是 Service interface 层吗，如果是的话 lib1可以直接依赖lib2 啊

**Comment by AngelRiven** [comment]
> lib2的职责是服务接口层吗，如果是的话lib1可以直接依赖lib2啊

不是呀，就是两个业务层lib，必须在基础库层下层接口，lib1和lib2里面里的类实现这个接口，然后才能ServiceLoader加载吗

**Comment by Knight-ZXW** [comment]
如果直接依赖 实现模块 那就没有必要 用 service provider  interface的设计模式了 。

spi的核心思想就是  只依赖 服务层 不依赖于具体的实现模块，因此 下层一个 接口层模块从设计思想是应该是必须的。

**Comment by Knight-ZXW** [comment]
lib1   lib2  ( impl module)
|          |
|------|
      |
      |
   interface module

**Comment by AngelRiven** [comment]
> 如果直接依赖实现模块那就没有必要用服务提供者接口的设计模式了。
> 
> spi的核心思想就是只依赖服务层不依赖于具体的实现模块，因此下沉（抽取）一个接口层模块从设计思想上来说应该是必须的。

OK，了解
