### ISSUE TITLE
不支持增量编译

### ISSUE THREAD

**Issue by sunddytwo** [meituan/WMRouter#74]
希望能支持下增量编译模式，代码多的话。会很卡，容易导致 
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by Leifzhang** [comment]
https://github.com/Leifzhang/Router-Android/tree/master/AutoRegister
https://juejin.im/post/5edce27c6fb9a047bf707ac2
其实我在我自己的工程内实现了  希望美团大佬可以参考下
