### ISSUE TITLE
对没有path的场景支持不够好

### ISSUE THREAD

**Issue by Caij** [meituan/WMRouter#78]
比如现在有uri:   https://www.meituan.com?id=1

@RouterUri(scheme = "https", host = "www.meituan.com", path = "")
Activity

没办法注册
![image](https://user-images.githubusercontent.com/8597839/85398416-c6dff580-b587-11ea-9e81-7d941e815c75.png)

没办法获取
![image](https://user-images.githubusercontent.com/8597839/85398445-d19a8a80-b587-11ea-91ff-5b82a409fa1f.png)

**Comment by jzj1993** [comment]
这种可以用正则表达式，也就是RouterRegex注解

**Comment by Caij** [comment]
@jzj1993 是可以这样做。  但是我觉得可以从兼容性上处理， 比如path为空 就认为是/ 处理。
