### ISSUE TITLE
自动生成的service初始化方法是在哪调用的？

### ISSUE THREAD

**Issue by certhon** [meituan/WMRouter#83]
![image](https://user-images.githubusercontent.com/17233918/96953100-e6316400-1522-11eb-8ceb-3dd2aaa1e02e.png)
那个router的初始化能从源码中看到。这个service注册的初始化init函数怎么没看到有地方调用啊，

**Comment by jzj1993** [comment]
Gradle插件借助ASM生成的代码调用，你可以通过反编译APK看到。
