### ISSUE TITLE
Could not resolve all artifacts for configuration ':classpath'.

### ISSUE THREAD

**Issue by Quincy-Ye** [meituan/WMRouter#93]
A problem occurred configuring root project 'WMRouterDemo'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.sankuai.waimai.router:plugin:1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/sankuai/waimai/router/plugin/1.1/plugin-1.1.pom
       - https://jcenter.bintray.com/com/sankuai/waimai/router/plugin/1.1/plugin-1.1.pom
       - https://repo.maven.apache.org/maven2/com/sankuai/waimai/router/plugin/1.1/plugin-1.1.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by jzj1993** [comment]
I think the reason we can not resolve the dependencies is that the jCenter has been closed. And we have publish a new version to mavenCentral. Check that in the release page, thanks.
