### ISSUE TITLE
fix: BaseTransform#foreachJar 执行俩遍

### ISSUE THREAD

**Issue by hcanyz** [meituan/WMRouter#99]
更新后，WMRouterTransform 过程 com.kronos.plugin.base.BaseTransform#foreachJar 方法执行了俩遍。

初步判断为 BaseTransform.kt:294 提交了一次单独任务，BaseTransform.kt:100 又提交了一次全部任务。

com.kronos.plugin.base.BaseTransform#foreachJarforeachClass 类似。

**Comment by Leifzhang** [comment]
容我测试下 看看
